require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RatesController do

  def mock_rate(stubs={})
    @mock_rate ||= mock_model(Rate, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all rates as @rates" do
      Rate.stub(:all) { [mock_rate] }
      get :index
      assigns(:rates).should eq([mock_rate])
    end
  end

  describe "GET show" do
    it "assigns the requested rate as @rate" do
      Rate.stub(:find).with("37") { mock_rate }
      get :show, :id => "37"
      assigns(:rate).should be(mock_rate)
    end
  end

  describe "GET new" do
    it "assigns a new rate as @rate" do
      Rate.stub(:new) { mock_rate }
      get :new
      assigns(:rate).should be(mock_rate)
    end
  end

  describe "GET edit" do
    it "assigns the requested rate as @rate" do
      Rate.stub(:find).with("37") { mock_rate }
      get :edit, :id => "37"
      assigns(:rate).should be(mock_rate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created rate as @rate" do
        Rate.stub(:new).with({'these' => 'params'}) { mock_rate(:save => true) }
        post :create, :rate => {'these' => 'params'}
        assigns(:rate).should be(mock_rate)
      end

      it "redirects to the created rate" do
        Rate.stub(:new) { mock_rate(:save => true) }
        post :create, :rate => {}
        response.should redirect_to(rate_url(mock_rate))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rate as @rate" do
        Rate.stub(:new).with({'these' => 'params'}) { mock_rate(:save => false) }
        post :create, :rate => {'these' => 'params'}
        assigns(:rate).should be(mock_rate)
      end

      it "re-renders the 'new' template" do
        Rate.stub(:new) { mock_rate(:save => false) }
        post :create, :rate => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rate" do
        Rate.stub(:find).with("37") { mock_rate }
        mock_rate.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :rate => {'these' => 'params'}
      end

      it "assigns the requested rate as @rate" do
        Rate.stub(:find) { mock_rate(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:rate).should be(mock_rate)
      end

      it "redirects to the rate" do
        Rate.stub(:find) { mock_rate(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(rate_url(mock_rate))
      end
    end

    describe "with invalid params" do
      it "assigns the rate as @rate" do
        Rate.stub(:find) { mock_rate(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:rate).should be(mock_rate)
      end

      it "re-renders the 'edit' template" do
        Rate.stub(:find) { mock_rate(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rate" do
      Rate.stub(:find).with("37") { mock_rate }
      mock_rate.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the rates list" do
      Rate.stub(:find) { mock_rate }
      delete :destroy, :id => "1"
      response.should redirect_to(rates_url)
    end
  end

end
